name: Bug-Report
description: Report a Bug to help us improve
title: 'Bug: '
labels: [bug]
assignees: [ ]
body:
  - type: markdown
    attributes:
      value: |
        You must use the issue template below when submitting a bug.
  - type: textarea
    attributes:
      label: Describe the Bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      placeholder: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: Logs
    attributes:
      label: Relevant Log Output
      placeholder: Bug reports that do not contain logs may be closed without warning.
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable add screenshots to help explain your problem.
      placeholder: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: input
    attributes:
      label: homekit-ratgdo Version
      placeholder: v0.9.0
    validations:
      required: true
  - type: input
    attributes:
      label: ratgdo Hardware Version
      placeholder: v2.5
    validations:
      required: false
