blank_issues_enabled: false
contact_links:
  - name: ratgdo v2.5 basic BACKORDER
    url: https://square.link/u/B5pW7OZW
    about: ratgdo v2.5 basic BACKORDER
  - name: ratgdo v2.5 control board with installation kit
    url: https://square.link/u/FKqlMSWT
    about: ratgdo v2.5 control board with installation kit
  - name: homekit-ratgdo flasher
    url: https://ratgdo.github.io/homekit-ratgdo/flash.html
    about: homekit-ratgdo flasher

    