name: Build Firmware - PlatformIO CI

on:
  repository_dispatch:
    types: [build-firmware]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Tag
        id: tag
        uses: JinoArch/get-latest-tag@latest

      - uses: actions/checkout@v3
        with:
            submodules: secplus
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: |
            pip install --upgrade pip
            pip install --upgrade platformio

      - name: Install External Dependencies
        run: |
          cd lib
          git clone https://github.com/argilo/secplus.git

      - name: Build PlatformIO Project
        run: pio run -e ratgdo_esp8266_hV25

      - name: Rename Firmware
        run: |
          mv .pio/build/ratgdo_esp8266_hV25/firmware.bin .pio/build/ratgdo_esp8266_hV25/homekit-ratgdo-${{ steps.tag.outputs.latestTag }}.bin
          mv .pio/build/ratgdo_esp8266_hV25/firmware.elf .pio/build/ratgdo_esp8266_hV25/homekit-ratgdo-${{ steps.tag.outputs.latestTag }}.elf

      - name: Attach Bundle
        uses: AButler/upload-release-assets@v3.0
        with:
          files: ".pio/build/ratgdo_esp8266_hV25/*.bin"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.tag.outputs.latestTag }}
      
      - name: Upload Release Asset
        uses: wow-actions/download-upload@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: https://github.com/donavanbecker/homekit-ratgdo/releases/download/${{ steps.tag.outputs.latestTag }}/homekit-ratgdo-${{ steps.tag.outputs.latestTag }}.bin
          dir: docs/firmware/
          commit_message: "Add Latest Firmware: homekit-ratgdo-${{ steps.tag.outputs.latestTag }}.bin"
    
      - name: Upload Firmware.bin
        uses: actions/upload-artifact@v4
        with:
          name: homekit-ratgdo-${{ steps.tag.outputs.latestTag }}.bin
          path: |
            .pio/build/ratgdo_esp8266_hV25/*.bin
    
      - name: Upload Firmware.elf
        uses: actions/upload-artifact@v4
        with:
          name: homekit-ratgdo-${{ steps.tag.outputs.latestTag }}.elf
          path: |
            .pio/build/ratgdo_esp8266_hV25/*.elf

      - name: Download Firmware.bin
        uses: actions/download-artifact@v4
        with:
          name: homekit-ratgdo-${{ steps.tag.outputs.latestTag }}.bin
          path: |
            docs/firmware/